# Generated by Django 4.2.2 on 2023-06-28 05:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stackbase', '0003_alter_question_date_created_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='likes',
            field=models.ManyToManyField(related_name='question_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
